language: generic

sudo: required

services: 
  - docker

before_install:
  - docker build -t philastrio/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true philastrio/react-test-app npm run test

after_success:
  - docker build -t philastrio/docker-frontend ./frontend
  - docker build -t philastrio/docker-backend ./backend
  - docker build -t philastrio/docker-nginx ./nginx
 
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push philastrio/docker-frontend
  - docker push philastrio/docker-backend
  - docker push philastrio/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-360987720711
  bucket_path: "docker-fullstack-app"
  on: 
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET_KEY